//
//  AppsController.swift
//  ModernCollectionViewSample
//
//  Created by Karen Minasyan on 10/4/20.
//

import UIKit

enum AppCategory {
    case top
    case popular
    case topPaid
    case topFree
    
}

struct AppCollection: Hashable {
    let title: String
    let apps: [AppModel]
    let sortIndex: Int
    let identifier = UUID()
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(identifier)
    }
}

class AppsController {
    
}

extension AppsController {
    func generateCollections() -> [AppCollection] {
        [AppCollection(title: "Popular Apps to Try",
                       apps: [
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this"),
                        AppModel(iconImage: UIImage(named: "image1")!,
                                 previewImage: UIImage(named: "image1")!,
                                 title: "VivaVideo - Video Maker",
                                 subTitle: "Movie Maker & Video Editor",
                                 commentText: "Rediscover this")
        ],
                       sortIndex: 0),
         AppCollection(title: "Popular Apps to Try",
                        apps: [
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this")
         ],
                        sortIndex: 1),
         AppCollection(title: "Popular Apps to Try",
                        apps: [
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this")
         ],
                        sortIndex: 2),
         AppCollection(title: "Popular Apps to Try",
                        apps: [
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this")
         ],
                        sortIndex: 3),
         AppCollection(title: "Popular Apps to Try",
                        apps: [
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this"),
                            AppModel(iconImage: UIImage(named: "image1")!,
                                     previewImage: UIImage(named: "image1")!,
                                     title: "VivaVideo - Video Maker",
                                     subTitle: "Movie Maker & Video Editor",
                                     commentText: "Rediscover this")
         ],
                        sortIndex: 3),
         
        ]
    }
}
