//
//  AppsController.swift
//  ModernCollectionViewSample
//
//  Created by Karen Minasyan on 10/4/20.
//

import UIKit

struct ItemCollection: Hashable {
    let title: String
    let items: [ItemModel]
    let sectionKindId: Int
    
    let identifier = UUID()
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(identifier)
    }
}

class ItemCollections {

    func getItemCollections() -> [ItemCollection] {
        [ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconName: "image1",
                                      previewImageName: "image1",
                                      title: "PicsArt Photo & Video Editor",
                                      subTitle: "Try the sketch effect",
                                      commentText: "get creative"),
                            ItemModel(iconName: "image1",
                                      previewImageName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconName: "image1",
                                      previewImageName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconName: "image1",
                                      previewImageName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconName: "image1",
                                      previewImageName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sectionKindId: 0),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconName: "picsart",
                                      title: "PicsArt Photo & Video Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "photocollage",
                                      title: "PhotoGrid Video Collage maker",
                                      subTitle: "Video Collage & Video Editor"),
                            ItemModel(iconName: "instagram",
                                      title: "Instagram",
                                      subTitle: "#2 in Photo & Video"),
                            ItemModel(iconName: "linkedin",
                                      title: "LinkedIn: Network & Job Finder",
                                      subTitle: "Connect, Apply & Get Hired"),
                            ItemModel(iconName: "messenger",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "pitperest",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "facebook",
                                      title: "Facebook",
                                      subTitle: "#2 in Social Networking"),
                            ItemModel(iconName: "skype",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "testflight",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                        ],
                        sectionKindId: 2),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconName: "tiktok",
                                      title: "TikTok - Trends Start Here",
                                      subTitle: "Videos, Music & Live Streams"),
                            ItemModel(iconName: "photolab",
                                      title: "Photo Lab: Picture Editor App",
                                      subTitle: "Art Face Editing, Filter Edit"),
                            ItemModel(iconName: "bazart",
                                      title: "Bazaart Photo Editor & Design",
                                      subTitle: "Collage, Edit, Cut, Paste Pics"),
                            ItemModel(iconName: "instagram",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "messenger",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "pitperest",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "facebook",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "skype",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "testflight",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                        ],
                        sectionKindId: 2),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconName: "picsartcolor",
                                      title: "PicsArt Color Paint",
                                      subTitle: "Sketch, Doodle, Create Pro Art"),
                            ItemModel(iconName: "twitter",
                                      title: "VivaVideo - Video Maker and Photo Editor and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "viber",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "vk",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "whatsup",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "youtube",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "messenger",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "pitperest",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "facebook",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "skype",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor")
                        ],
                        sectionKindId: 1),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconName: "image1",
                                      title: "Viva",
                                      subTitle: "Movie"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                            ItemModel(iconName: "image1",
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor"),
                        ],
                        sectionKindId: 3),
         ItemCollection(title: "Top Categories",
                        items: [
                            ItemModel(iconName: "image1",
                                      title: "Photo & Video"),
                            ItemModel(iconName: "image1",
                                      title: "Social Networking"),
                            ItemModel(iconName: "image1",
                                      title: "Utilities"),
                            ItemModel(iconName: "image1",
                                      title: "Productivity"),
                            ItemModel(iconName: "image1",
                                      title: "Health & Fitness"),
                            ItemModel(iconName: "image1",
                                      title: "Music")
                        ],
                        sectionKindId: 4)
        ]
    }
}
