//
//  AppsController.swift
//  ModernCollectionViewSample
//
//  Created by Karen Minasyan on 10/4/20.
//

import UIKit

struct ItemCollection: Hashable {
    let title: String
    let items: [ItemModel]
    let sectionKindId: Int
    
    let identifier = UUID()
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(identifier)
    }
}

class ItemCollections {
    
    func getItemCollections() -> [ItemCollection] {
        [ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "get creative"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sectionKindId: 0),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sectionKindId: 2),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "Viva",
                                      subTitle: "Movie",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sectionKindId: 1),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "Viva",
                                      subTitle: "Movie",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker and Photo Editor",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sectionKindId: 3),
         ItemCollection(title: "Top Categories",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      title: "Photo & Video"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      title: "Social Networking"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      title: "Utilities"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      title: "Productivity"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      title: "Health & Fitness"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      title: "Music")
                        ],
                        sectionKindId: 4)
        ]
    }
}
