//
//  AppsController.swift
//  ModernCollectionViewSample
//
//  Created by Karen Minasyan on 10/4/20.
//

import UIKit

enum AppCategory {
    case top
    case popular
    case topPaid
    case topFree
    
}

struct ItemCollection: Hashable {
    let title: String
    let items: [ItemModel]
    let sortIndex: Int

    let identifier = UUID()

    func hash(into hasher: inout Hasher) {
        hasher.combine(identifier)
    }
}

class ItemCollections {

    func getItemCollections() -> [ItemCollection] {
        [ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sortIndex: 0),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sortIndex: 1),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sortIndex: 2),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sortIndex: 3),
         ItemCollection(title: "Popular Apps to Try",
                        items: [
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this"),
                            ItemModel(iconImage: UIImage(named: "image1")!,
                                      previewImage: UIImage(named: "image1")!,
                                      title: "VivaVideo - Video Maker",
                                      subTitle: "Movie Maker & Video Editor",
                                      commentText: "Rediscover this")
                        ],
                        sortIndex: 3),
         ItemCollection(title: "Apps for Professionals", items: [
            ItemModel(iconImage: UIImage(named: "image1")!,
                      previewImage: UIImage(named: "image1")!,
                      title: "Apps for entrepreneurs"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      previewImage: UIImage(named: "image1")!,
                      title: "Apps for entrepreneurs"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      previewImage: UIImage(named: "image1")!,
                      title: "Apps for entrepreneurs"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      previewImage: UIImage(named: "image1")!,
                      title: "Apps for entrepreneurs"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      previewImage: UIImage(named: "image1")!,
                      title: "Apps for entrepreneurs"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      previewImage: UIImage(named: "image1")!,
                      title: "Apps for entrepreneurs")
         ],
         sortIndex: 3),
         ItemCollection(title: "Top Categories", items: [
            ItemModel(iconImage: UIImage(named: "image1")!,
                      title: "Photo & Video"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      title: "Social Networking"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      title: "Utilities"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      title: "Productivity"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      title: "Health & Fitness"),
            ItemModel(iconImage: UIImage(named: "image1")!,
                      title: "Music")
         ],
         sortIndex: 4)
        ]
    }
}
